apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-microservice
  namespace: sdk
  labels:
    app: api-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-microservice
  template:
    metadata:
      labels:
        app: api-microservice
    spec:
      containers:
      - name: api-microservice
        image: ashpect/apimicroservice:latest
        ports:
        - containerPort: 3002

---
apiVersion: v1
kind: Service
metadata:
  name: api-microservice
  namespace: sdk
  labels:
    app: api-microservice
spec:
  type: ClusterIP
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
  selector:
    app: api-microservice