apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prover-hpa
  namespace: sdk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: k8s-prover
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
