apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-prover
  namespace: sdk
  labels:
    app: prover
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prover
  template:
    metadata:
      labels:
        app: prover
    spec:
      containers:
        - name: prover
          image: ashpect/proversnark:latest
          # imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: k8s-prover-secret
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
            - name: prover-pvc
              mountPath: /prover/artifacts
          resources:
            requests:
              cpu: 1
              memory: 4Gi
            limits:
              cpu: 2
              memory: 8Gi
      volumes:
        - name: prover-pvc
          persistentVolumeClaim:
            claimName: prover-pvc
  
---
apiVersion: v1
kind: Service
metadata:
  name: prover-nodeport
  namespace: sdk
spec:
  type: NodePort
  selector:
    app: prover
  ports:
    - port: 3000      
      targetPort: 3000   
      nodePort: 31000